// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.4
// source: meshgateway/meshgateway.proto

package meshgateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeTxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId int64 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (x *SubscribeTxReq) Reset() {
	*x = SubscribeTxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshgateway_meshgateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTxReq) ProtoMessage() {}

func (x *SubscribeTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_meshgateway_meshgateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTxReq.ProtoReflect.Descriptor instead.
func (*SubscribeTxReq) Descriptor() ([]byte, []int) {
	return file_meshgateway_meshgateway_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeTxReq) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type SubscribeTxResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *SubscribeTxResp) Reset() {
	*x = SubscribeTxResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshgateway_meshgateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTxResp) ProtoMessage() {}

func (x *SubscribeTxResp) ProtoReflect() protoreflect.Message {
	mi := &file_meshgateway_meshgateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTxResp.ProtoReflect.Descriptor instead.
func (*SubscribeTxResp) Descriptor() ([]byte, []int) {
	return file_meshgateway_meshgateway_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeTxResp) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

var File_meshgateway_meshgateway_proto protoreflect.FileDescriptor

var file_meshgateway_meshgateway_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x65, 0x73, 0x68, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6d, 0x65,
	0x73, 0x68, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x6d, 0x65, 0x73, 0x68, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x2a, 0x0a, 0x0e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x78, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x78, 0x32, 0x59, 0x0a, 0x0b, 0x6d,
	0x65, 0x73, 0x68, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x78, 0x12, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x68,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x54, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x78,
	0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x68,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshgateway_meshgateway_proto_rawDescOnce sync.Once
	file_meshgateway_meshgateway_proto_rawDescData = file_meshgateway_meshgateway_proto_rawDesc
)

func file_meshgateway_meshgateway_proto_rawDescGZIP() []byte {
	file_meshgateway_meshgateway_proto_rawDescOnce.Do(func() {
		file_meshgateway_meshgateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshgateway_meshgateway_proto_rawDescData)
	})
	return file_meshgateway_meshgateway_proto_rawDescData
}

var file_meshgateway_meshgateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshgateway_meshgateway_proto_goTypes = []interface{}{
	(*SubscribeTxReq)(nil),  // 0: meshgateway.SubscribeTxReq
	(*SubscribeTxResp)(nil), // 1: meshgateway.SubscribeTxResp
}
var file_meshgateway_meshgateway_proto_depIdxs = []int32{
	0, // 0: meshgateway.meshgateway.SubscribeTx:input_type -> meshgateway.SubscribeTxReq
	1, // 1: meshgateway.meshgateway.SubscribeTx:output_type -> meshgateway.SubscribeTxResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshgateway_meshgateway_proto_init() }
func file_meshgateway_meshgateway_proto_init() {
	if File_meshgateway_meshgateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshgateway_meshgateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeTxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshgateway_meshgateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeTxResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshgateway_meshgateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshgateway_meshgateway_proto_goTypes,
		DependencyIndexes: file_meshgateway_meshgateway_proto_depIdxs,
		MessageInfos:      file_meshgateway_meshgateway_proto_msgTypes,
	}.Build()
	File_meshgateway_meshgateway_proto = out.File
	file_meshgateway_meshgateway_proto_rawDesc = nil
	file_meshgateway_meshgateway_proto_goTypes = nil
	file_meshgateway_meshgateway_proto_depIdxs = nil
}
